-- Importar códigos CID-10 de dermatologia
-- Categoria: Doenças da Pele e Tecido Subcutâneo

INSERT INTO cid_codes (code, description, category) VALUES
('C43', 'Melanoma maligno da pele', 'Neoplasias'),
('C43.0', 'Melanoma maligno do lábio', 'Neoplasias'),
('C43.1', 'Melanoma maligno da pálpebra, incluindo as comissuras palpebrais', 'Neoplasias'),
('C43.2', 'Melanoma maligno da orelha e do conduto auditivo externo', 'Neoplasias'),
('C43.3', 'Melanoma maligno de outras partes e partes não especificadas da face', 'Neoplasias'),
('C43.4', 'Melanoma maligno do couro cabeludo e do pescoço', 'Neoplasias'),
('C43.5', 'Melanoma maligno do tronco', 'Neoplasias'),
('C43.6', 'Melanoma maligno do membro superior, incluindo ombro', 'Neoplasias'),
('C43.7', 'Melanoma maligno do membro inferior, incluindo quadril', 'Neoplasias'),
('C43.8', 'Melanoma maligno invasivo da pele', 'Neoplasias'),
('C43.9', 'Melanoma maligno de pele, não especificado', 'Neoplasias'),
('C44', 'Outras neoplasias malignas da pele', 'Neoplasias'),
('C44.0', 'Neoplasia maligna da pele do lábio', 'Neoplasias'),
('C44.1', 'Neoplasia maligna da pele da pálpebra, incluindo o canto', 'Neoplasias'),
('C44.2', 'Neoplasia maligna da pele da orelha e do conduto auditivo externo', 'Neoplasias'),
('C44.3', 'Neoplasia maligna da pele de outras partes e de partes não especificadas da face', 'Neoplasias'),
('C44.4', 'Neoplasia maligna da pele do couro cabeludo e do pescoço', 'Neoplasias'),
('C44.5', 'Neoplasia maligna da pele do tronco', 'Neoplasias'),
('C44.6', 'Neoplasia maligna da pele do membro superior, incluindo ombro', 'Neoplasias'),
('C44.7', 'Neoplasia maligna da pele do membro inferior, incluindo quadril', 'Neoplasias'),
('C44.8', 'Neoplasia maligna invasiva da pele', 'Neoplasias'),
('C44.9', 'Neoplasia maligna de pele, não especificada', 'Neoplasias'),
('L98', 'Outras afecções da pele e do tecido subcutâneo não classificadas em outra parte', 'Doenças da Pele e Tecido Subcutâneo'),
('L98.0', 'Granuloma piogênico', 'Doenças da Pele e Tecido Subcutâneo'),
('L98.1', 'Dermatite factícia', 'Doenças da Pele e Tecido Subcutâneo'),
('L98.2', 'Dermatose neutrofílica febril [Sweet]', 'Doenças da Pele e Tecido Subcutâneo'),
('L98.3', 'Celulite eosinofílica [Wells]', 'Doenças da Pele e Tecido Subcutâneo'),
('L98.4', 'Úlcera crônica da pele, não classificada em outra parte', 'Doenças da Pele e Tecido Subcutâneo'),
('L98.5', 'Mucinose da pele', 'Doenças da Pele e Tecido Subcutâneo'),
('L98.6', 'Outras afecções infiltrativas da pele e do tecido subcutâneo', 'Doenças da Pele e Tecido Subcutâneo'),
('L98.8', 'Outras afecções especificadas da pele e do tecido subcutâneo', 'Doenças da Pele e Tecido Subcutâneo'),
('L98.9', 'Afecções da pele e do tecido subcutâneo, não especificados', 'Doenças da Pele e Tecido Subcutâneo');
